---

SNSTopic:
  Type: AWS::SNS::Topic
  Properties:
    DisplayName: "fitment-stack-alarms"
    TopicName: "fitment-stack-alarms"
    Subscription:
      -
        Protocol: "lambda"
        Endpoint:
          Fn::Join:
          - ""
          - - "arn:aws:lambda:"
            - Ref: "AWS::Region"
            - ":"
            - Ref: "AWS::AccountId"
            - ":function:slack-notifications-lambda-${opt:stage, self:provider.stage}-sendMessageToSlack"

ApiGateway4XXError:
  Type: AWS::CloudWatch::Alarm
  Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopic
      AlarmName:
        Fn::Join: [ "-", [ "ApiGateway", "fitment", "4XXError" ] ]
      ComparisonOperator: "GreaterThanThreshold"
      Dimensions:
        - Name: ApiName
          Value: ${opt:stage, self:provider.stage}-fitment-lambda
      EvaluationPeriods: 1
      MetricName: "4XXError"
      Namespace: "AWS/ApiGateway"
      Period: 60
      Statistic: "Sum"
      Threshold: "0"
      TreatMissingData: "notBreaching"

ApiGateway5XXError:
  Type: AWS::CloudWatch::Alarm
  Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopic
      AlarmName:
        Fn::Join: [ "-", [ "ApiGateway", "fitment", "5XXError" ] ]
      ComparisonOperator: "GreaterThanThreshold"
      Dimensions:
        - Name: ApiName
          Value: ${opt:stage, self:provider.stage}-fitment-lambda
      EvaluationPeriods: 1
      MetricName: "5XXError"
      Namespace: "AWS/ApiGateway"
      Period: 60
      Statistic: "Sum"
      Threshold: "0"
      TreatMissingData: "notBreaching"

ApiGatewayLatency:
  Type: AWS::CloudWatch::Alarm
  Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopic
      AlarmName:
        Fn::Join: [ "-", [ "ApiGateway", "fitment", "Latency" ] ]
      ComparisonOperator: "GreaterThanThreshold"
      Dimensions:
        - Name: ApiName
          Value: ${opt:stage, self:provider.stage}-fitment-lambda
      EvaluationPeriods: 1
      MetricName: "Latency"
      Namespace: "AWS/ApiGateway"
      Period: 60
      Statistic: "Average"
      Threshold: "100"
      TreatMissingData: "notBreaching"


s3bucket4xxErrors:
  Type: AWS::CloudWatch::Alarm
  Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopic
      AlarmName:
        Fn::Join: [ "-", [ "s3", "fitment", "4XXError" ] ]
      ComparisonOperator: "GreaterThanThreshold"
      Dimensions:
        - Name: BucketName
          Value: '${self:provider.environment.BUCKET}'
        - Name: FilterId
          Value: EntireBucket
      EvaluationPeriods: 1
      MetricName: "4XXError"
      Namespace: "AWS/S3"
      Period: 60
      Statistic: "Average"
      Threshold: "1"
      TreatMissingData: "notBreaching"

s3bucket5xxErrors:
  Type: AWS::CloudWatch::Alarm
  Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopic
      AlarmName:
        Fn::Join: [ "-", [ "s3", "fitment", "5XXError" ] ]
      ComparisonOperator: "GreaterThanThreshold"
      Dimensions:
        - Name: BucketName
          Value: '${self:provider.environment.BUCKET}'
        - Name: FilterId
          Value: EntireBucket
      EvaluationPeriods: 1
      MetricName: "5XXError"
      Namespace: "AWS/S3"
      Period: 60
      Statistic: "Average"
      Threshold: "1"
      TreatMissingData: "notBreaching"

s3bucketTotalRequestLatency:
  Type: AWS::CloudWatch::Alarm
  Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSTopic
      AlarmName:
        Fn::Join: [ "-", [ "s3", "fitment", "TotalRequestLatency" ] ]
      ComparisonOperator: "GreaterThanThreshold"
      Dimensions:
        - Name: BucketName
          Value: '${self:provider.environment.BUCKET}'
        - Name: FilterId
          Value: EntireBucket
      EvaluationPeriods: 1
      MetricName: "TotalRequestLatency"
      Namespace: "AWS/S3"
      Period: 60
      Statistic: "Maximum"
      Threshold: "100"
      TreatMissingData: "notBreaching"
