---
version: 2
plan:
  project-key: GAASPIP
  key: GSGFLV2A
  name: Fitment Lambda V2

docker: node:10-slim

stages:
  - Build:
    - Build
  - Sonar:
      manual: true
      jobs:
        - Sonar


Build:
  tasks:
    - clean
    - script:
        - scripts/build.sh
    - test-parser:
        type: mocha
        test-results: 'test-report.json'
  final-tasks:
    - script:
      - echo "Final task"
      - scripts/notifications.sh build
  artifacts:
     - name: package.json
       pattern: package.json
     - name: scripts
       pattern: scripts/**


Sonar:
  tasks:
    - script:
        - scripts/sonar.sh
  final-tasks:
    - script:
      - echo "Final task Sonar"

---
version: 2
deployment:
  name: Fitment Lambda
  source-plan: GAASPIP-GSGFLV2A
  

release-naming:
  next-version-name: 1.0.${bamboo.buildNumber}
  # auto-increment-variables:
  #   - release-number


environments:
  - Test
  # - Staging
  # - Prod


Test:
  variables:
    gaas_deploy_stage: test
  docker:
    image: node:10-slim
  tasks:
    - clean
    - artifact-download:
        destination: .
    - script:
        - scripts/deploy.sh
  final-tasks:
    - script:
      - echo "Final task"
      - scripts/notifications.sh deploy


# Staging:
#   variables:
#     gaas_deploy_stage: prod
#   docker:
#     image: node:10-slim
#   tasks:
#     - clean
#     - artifact-download:
#         destination: .
#     - script:
#         - scripts/deploy.sh
#   final-tasks:
#     - script:
#       - echo "Final task"
#       - scripts/notifications.sh deploy


# Prod:
#   variables:
#     gaas_deploy_stage: prod
#   docker:
#     image: node:10-slim
#   tasks:
#     - clean
#     - artifact-download:
#         destination: .
#     - script:
#         - scripts/deploy.sh
#   final-tasks:
#     - script:
#       - echo "Final task"
#       - scripts/notifications.sh deploy