---
version: 2
plan:
  project-key: GAASPIP
  key: GSGFLV2A
  name: Fitment Lambda V2a

docker: nexus.goodyear.eu:9000/gaas/base:1.0.1

stages:
  - Build:
    - Build
  - Sonar:
      manual: true
      jobs:
        - Sonar

Build:
  tasks:
    - clean
    - script:
        - scripts/build.sh
    - test-parser:
        type: mocha
        test-results: 'test-report.json'
  final-tasks:
    - script:
      - echo "Final task"
  artifacts:
     - name: package.json
       pattern: package.json
    #  - name: deploy.sh
    #    pattern: scripts/deploy.sh  
     - name: scripts
       pattern: scripts/**


Sonar:
  tasks:
    - script:
        - scripts/sonar.sh
  final-tasks:
    - script:
      - echo "Final task Sonar"

---
version: 2
# docker: nexus.goodyear.eu:9000/gaas/base:1.0.1
deployment:
  name: Example Lambda
  source-plan: GAASPIP-GSGELMRV2
  

release-naming:
  next-version-name: 1.0.${bamboo.buildNumber}
  # auto-increment-variables:
  #   - release-number


environments:
  - Test
  - Staging
  # - Production


Test:
  variables:
    gaas_deploy_stage: test
  docker: nexus.goodyear.eu:9000/gaas/base:1.0.1
  tasks:
    - clean
    - artifact-download:
        destination: .
    - script:
        - pwd
        - ls -la
        - scripts/deploy.sh
  final-tasks:
    - script:
      - echo "Clean up AWS credentials, send deploy status"


Staging:
  variables:
    gaas_deploy_stage: test
  docker: nexus.goodyear.eu:9000/gaas/base:1.0.1
  tasks:
    - clean
    - artifact-download:
        destination: .
    - script:
        - pwd
        - ls -la
        - scripts/deploy.sh
  final-tasks:
    - script:
      - echo "Clean up AWS credentials, send deploy status"


# Production:
#   variables:
#     gaas_deploy_stage: test
#   docker: nexus.goodyear.eu:9000/gaas/base:1.0.1
#   tasks:
#     - clean
#     - artifact-download:
#         destination: /
#     - script:
#         - bash ./deploy.sh || ./slack.sh deploy
#   final-tasks:
#     - script:
#       - echo "Final task Test env"

# # ---
# # version: 2
# # plan:
# #   key: GSGELMR

# # plan-permissions:
# #   - users:
# #       - voshchypko@intellias.com
# #     permissions:
# #       - view
# #       - edit
# #       - build
# #       - admin
# #       # - clone


# # ---
# # version: 2
# # deployment:
# #   name: Example Lambda
# #   source-plan: GAASPIP-GSGELMR

# # # deployment-permissions:
# # #   - users:
# # #       - voshchypko@intellias.com
# # #       - oladnov@intellias.com
# # #     permissions:
# # #       - view
# # #       - edit

# # # default-environment-permissions:
# # #   - users:
# # #       - voshchypko@intellias.com
# # #       - oladnov@intellias.com
# # #     permissions:
# # #       - view
# # #       - edit
# # #       - deploy

# # environment-permissions:
# #   - Test:
# #       - users:
# #           - voshchypko@intellias.com
# #           - oladnov@intellias.com
# #         permissions:
# #           - view
# #   - Staging:
# #       - users:
# #           - voshchypko@intellias.com
# #           - oladnov@intellias.com
# #         permissions:
# #           - view
# #           - edit
# #   - Production:
# #       - users:
# #           - voshchypko@intellias.com
# #           - oladnov@intellias.com
# #         permissions:
# #           - view
# #           - edit
# #           - deploy


# # https://jira.atlassian.com/browse/BAM-20553?attachmentViewMode=gallery