vpc: ""
alertNotifications: ""
Resources:

  requestBodyValidator:
    Type: 'AWS::ApiGateway::RequestValidator'
    Properties:
      Name: reqBodyValidator
      RestApiId:
        Ref: ApiGatewayRestApi
      ValidateRequestBody: true
      ValidateRequestParameters: false
  requestParametersValidator:
    Type: 'AWS::ApiGateway::RequestValidator'
    Properties:
      Name: reqParamsValidator
      RestApiId:
        Ref: ApiGatewayRestApi
      ValidateRequestBody: false
      ValidateRequestParameters: true

  SNSTopic: ${file(./sls/monitoring.yml):SNSTopic}

  ApiGateway4XXError: ${file(./sls/monitoring.yml):ApiGateway4XXError}
  ApiGateway5XXError: ${file(./sls/monitoring.yml):ApiGateway5XXError}
  ApiGatewayLatency: ${file(./sls/monitoring.yml):ApiGatewayLatency}

  s3bucket4xxErrors: ${file(./sls/monitoring.yml):s3bucket4xxErrors}
  s3bucket5xxErrors: ${file(./sls/monitoring.yml):s3bucket5xxErrors}
  s3bucketTotalRequestLatency: ${file(./sls/monitoring.yml):s3bucketTotalRequestLatency}

customDomain:
  enabled: false
