alertNotifications: ""
Resources:
  requestBodyValidator:
    Type: 'AWS::ApiGateway::RequestValidator'
    Properties:
      Name: reqBodyValidator
      RestApiId:
        Ref: ApiGatewayRestApi
      ValidateRequestBody: true
      ValidateRequestParameters: false
  requestParametersValidator:
    Type: 'AWS::ApiGateway::RequestValidator'
    Properties:
      Name: reqParamsValidator
      RestApiId:
        Ref: ApiGatewayRestApi
      ValidateRequestBody: false
      ValidateRequestParameters: true
customDomain:
  domainName: localhost
  basePath: example
  endpointType: regional
  certificateName: localhost
  stage: '${opt:stage, self:provider.stage}'
  createRoute53Record: true
  enabled: false
